<?php

declare(strict_types=1);

namespace Mailika\Filter;

use Mailika\Auth\MailboxCredentials;

final readonly class ManageSieveClient
{
    private const OWNERSHIP_MARKER = '# Generated by Mailika';

    public function publish(
        ManageSieveConnectionInterface $connection,
        MailboxCredentials $credentials,
        string $scriptName,
        string $script,
        bool $startTls,
    ): SievePublishResult {
        try {
            $capabilities = $this->expectOk($this->readResponse($connection))->capabilities;

            if ($startTls) {
                $this->requireCapability($capabilities, 'STARTTLS');
                $connection->write("STARTTLS\r\n");
                $this->expectOk($this->readResponse($connection));
                $connection->enableTls();
                $connection->write("CAPABILITY\r\n");
                $capabilities = $this->expectOk($this->readResponse($connection))->capabilities;
            }

            $this->requireSaslPlain($capabilities);
            $this->authenticatePlain($connection, $credentials);
            $this->assertScriptCanBeReplaced($connection, $scriptName);
            $this->putScript($connection, $scriptName, $script);
            $this->setActive($connection, $scriptName);
            $this->logout($connection);
        } finally {
            $connection->close();
        }

        return new SievePublishResult(true, 'Filters published to ManageSieve.');
    }

    /**
     * @return array<string, string>
     */
    public function capabilities(ManageSieveConnectionInterface $connection, bool $startTls): array
    {
        try {
            $capabilities = $this->expectOk($this->readResponse($connection))->capabilities;
            if (!$startTls) {
                return $capabilities;
            }

            $this->requireCapability($capabilities, 'STARTTLS');
            $connection->write("STARTTLS\r\n");
            $this->expectOk($this->readResponse($connection));
            $connection->enableTls();
            $connection->write("CAPABILITY\r\n");
            return $this->expectOk($this->readResponse($connection))->capabilities;
        } finally {
            $connection->close();
        }
    }

    private function authenticatePlain(
        ManageSieveConnectionInterface $connection,
        MailboxCredentials $credentials,
    ): void {
        $initialResponse = base64_encode("\0" . $credentials->email . "\0" . $credentials->password);
        $connection->write('AUTHENTICATE "PLAIN" ' . $this->quoted($initialResponse) . "\r\n");
        $this->expectOk($this->readResponse($connection));
    }

    private function assertScriptCanBeReplaced(ManageSieveConnectionInterface $connection, string $scriptName): void
    {
        $connection->write('GETSCRIPT ' . $this->quoted($scriptName) . "\r\n");
        $response = $this->readResponse($connection);

        if ($response->ok()) {
            if ($this->isMailikaOwnedScript($response->lines)) {
                return;
            }

            throw new SievePublishException('Existing ManageSieve script was not generated by Mailika.');
        }

        if ($response->status === 'NO' && $this->isMissingScriptResponse($response->message)) {
            return;
        }

        throw new SievePublishException('Unable to verify existing ManageSieve script ownership.');
    }

    private function putScript(ManageSieveConnectionInterface $connection, string $scriptName, string $script): void
    {
        $bytes = strlen($script);
        if ($bytes === 0) {
            throw new SievePublishException('Generated Sieve script is empty.');
        }

        $connection->write('PUTSCRIPT ' . $this->quoted($scriptName) . ' {' . $bytes . "+}\r\n" . $script);
        $this->expectOk($this->readResponse($connection));
    }

    private function setActive(ManageSieveConnectionInterface $connection, string $scriptName): void
    {
        $connection->write('SETACTIVE ' . $this->quoted($scriptName) . "\r\n");
        $this->expectOk($this->readResponse($connection));
    }

    private function logout(ManageSieveConnectionInterface $connection): void
    {
        $connection->write("LOGOUT\r\n");
        $this->expectOk($this->readResponse($connection));
    }

    /**
     * @param list<string> $lines
     */
    private function isMailikaOwnedScript(array $lines): bool
    {
        foreach ($lines as $line) {
            if (str_contains($line, self::OWNERSHIP_MARKER)) {
                return true;
            }
        }

        return false;
    }

    private function isMissingScriptResponse(string $message): bool
    {
        $message = strtoupper($message);

        return str_contains($message, 'NONEXISTENT')
            || str_contains($message, 'NOT FOUND')
            || str_contains($message, 'DOES NOT EXIST');
    }

    private function readResponse(ManageSieveConnectionInterface $connection): ManageSieveResponse
    {
        $lines = [];
        $capabilities = [];

        for ($lineCount = 0; $lineCount < 1000; $lineCount++) {
            $line = rtrim($connection->readLine(), "\r\n");

            if (preg_match('/^\{(\d+)\}$/', $line, $matches) === 1) {
                $literal = $connection->readBytes((int) $matches[1]);
                $lines[] = $literal;
                continue;
            }

            if (preg_match('/^(OK|NO|BYE)\b(.*)$/i', $line, $matches) === 1) {
                return new ManageSieveResponse(
                    strtoupper($matches[1]),
                    trim($matches[2]),
                    $capabilities,
                    $lines,
                );
            }

            $lines[] = $line;
            $capability = $this->capabilityFromLine($line);
            if ($capability !== null) {
                $capabilities[$capability[0]] = $capability[1];
            }
        }

        throw new SievePublishException('ManageSieve response exceeded the line limit.');
    }

    private function expectOk(ManageSieveResponse $response): ManageSieveResponse
    {
        if ($response->ok()) {
            return $response;
        }

        throw new SievePublishException('ManageSieve server rejected the request.');
    }

    /**
     * @param array<string, string> $capabilities
     */
    private function requireCapability(array $capabilities, string $name): void
    {
        if (!array_key_exists(strtoupper($name), $capabilities)) {
            throw new SievePublishException('ManageSieve server does not advertise ' . $name . '.');
        }
    }

    /**
     * @param array<string, string> $capabilities
     */
    private function requireSaslPlain(array $capabilities): void
    {
        $sasl = strtoupper($capabilities['SASL'] ?? '');
        $mechanisms = preg_split('/\s+/', $sasl) ?: [];
        if (!in_array('PLAIN', $mechanisms, true)) {
            throw new SievePublishException('ManageSieve server does not advertise SASL PLAIN.');
        }
    }

    /**
     * @return array{0:string, 1:string}|null
     */
    private function capabilityFromLine(string $line): ?array
    {
        if (preg_match('/^"((?:\\\\.|[^"\\\\])*)"(?:\s+"((?:\\\\.|[^"\\\\])*)")?$/', $line, $matches) !== 1) {
            return null;
        }

        return [
            strtoupper($this->unquoted($matches[1])),
            isset($matches[2]) ? $this->unquoted($matches[2]) : '',
        ];
    }

    private function quoted(string $value): string
    {
        $value = (string) preg_replace('/[\x00-\x1F\x7F]/', ' ', $value);
        return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
    }

    private function unquoted(string $value): string
    {
        return stripcslashes($value);
    }
}
