<?php

declare(strict_types=1);

namespace Mailika\Filter;

final readonly class SieveScriptCompiler
{
    /**
     * @param list<SieveRule> $rules
     */
    public function compile(array $rules): string
    {
        $enabledRules = array_values(array_filter($rules, static fn (SieveRule $rule): bool => $rule->enabled));
        if ($enabledRules === []) {
            return "# Generated by Mailika\n# No enabled rules.\n";
        }

        $extensions = $this->extensions($enabledRules);
        $lines = ['# Generated by Mailika'];

        if ($extensions !== []) {
            $lines[] = 'require [' . implode(', ', array_map($this->quote(...), $extensions)) . '];';
        }

        foreach ($enabledRules as $rule) {
            $lines[] = '';
            $lines[] = '# ' . $this->comment($rule->name);
            $lines[] = 'if ' . $this->condition($rule) . ' {';
            $lines[] = '    ' . $this->action($rule);

            if ($rule->stopProcessing) {
                $lines[] = '    stop;';
            }

            $lines[] = '}';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param list<SieveRule> $rules
     * @return list<string>
     */
    private function extensions(array $rules): array
    {
        $extensions = [];
        foreach ($rules as $rule) {
            if ($rule->action === 'fileinto') {
                $extensions['fileinto'] = 'fileinto';
            }

            if ($rule->action === 'vacation') {
                $extensions['vacation'] = 'vacation';
            }

            if ($rule->matchField === 'body') {
                $extensions['body'] = 'body';
            }
        }

        ksort($extensions);

        return array_values($extensions);
    }

    private function condition(SieveRule $rule): string
    {
        $operator = $rule->matchOperator === 'is' ? ':is' : ':contains';
        $value = $this->quote($rule->matchValue);

        $condition = match ($rule->matchField) {
            'from' => 'header ' . $operator . ' "From" ' . $value,
            'to' => 'header ' . $operator . ' ["To", "Cc"] ' . $value,
            'body' => 'body ' . $operator . ' ' . $value,
            'any_header' => 'header ' . $operator . ' ["From", "To", "Cc", "Subject"] ' . $value,
            default => 'header ' . $operator . ' "Subject" ' . $value,
        };

        if ($rule->action !== 'vacation' || $rule->vacationExcludedSenders === []) {
            return $condition;
        }

        return 'allof(' . $condition . ', not header :contains "From" '
            . $this->stringList($rule->vacationExcludedSenders) . ')';
    }

    private function action(SieveRule $rule): string
    {
        return match ($rule->action) {
            'discard' => 'discard;',
            'keep' => 'keep;',
            'redirect' => 'redirect ' . $this->quote((string) $rule->actionTarget) . ';',
            'vacation' => 'vacation' . $this->vacationOptions($rule) . ' '
                . $this->quote((string) $rule->actionTarget) . ';',
            default => 'fileinto ' . $this->quote((string) $rule->actionTarget) . ';',
        };
    }

    private function vacationOptions(SieveRule $rule): string
    {
        $options = [];

        if ($rule->vacationAddresses !== []) {
            $options[] = ':addresses ' . $this->stringList($rule->vacationAddresses);
        }

        if ($rule->vacationDays !== null) {
            $options[] = ':days ' . $rule->vacationDays;
        }

        if ($rule->vacationSubject !== null) {
            $options[] = ':subject ' . $this->quote($rule->vacationSubject);
        }

        return $options === [] ? '' : ' ' . implode(' ', $options);
    }

    /**
     * @param list<string> $values
     */
    private function stringList(array $values): string
    {
        if (count($values) === 1) {
            return $this->quote($values[0]);
        }

        return '[' . implode(', ', array_map($this->quote(...), $values)) . ']';
    }

    private function quote(string $value): string
    {
        $value = (string) preg_replace('/[\x00-\x1F\x7F]/', ' ', $value);
        return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
    }

    private function comment(string $value): string
    {
        $value = (string) preg_replace('/[\x00-\x1F\x7F]/', ' ', $value);
        return str_replace(['*/', '/*'], '', $value);
    }
}
