<?php

declare(strict_types=1);

namespace Mailika\Filter;

final readonly class SieveScriptAnalyzer
{
    private const OWNERSHIP_MARKER = '# Generated by Mailika';
    private const MAX_BYTES = 65_536;

    /** @var list<string> */
    private const KNOWN_ACTIONS = [
        'addflag',
        'deleteheader',
        'discard',
        'ereject',
        'execute',
        'fileinto',
        'keep',
        'notify',
        'pipe',
        'redirect',
        'reject',
        'removeflag',
        'replace',
        'set',
        'setflag',
        'vacation',
    ];

    /** @var list<string> */
    private const UNSUPPORTED_ACTIONS = [
        'addflag',
        'deleteheader',
        'ereject',
        'execute',
        'notify',
        'pipe',
        'reject',
        'removeflag',
        'replace',
        'set',
        'setflag',
    ];

    public function analyze(string $script): SieveScriptAnalysis
    {
        $bytes = strlen($script);
        $lines = $script === '' ? 0 : substr_count($script, "\n") + 1;
        $warnings = [];

        if ($bytes === 0) {
            $warnings[] = 'Script is empty.';
        }

        if ($bytes > self::MAX_BYTES) {
            $warnings[] = 'Script exceeds the 64 KiB inspection limit.';
            $script = substr($script, 0, self::MAX_BYTES);
        }

        if (preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/', $script) === 1) {
            $warnings[] = 'Script contains control characters outside normal whitespace.';
        }

        $withoutComments = $this->withoutComments($script);
        $tokenView = $this->withoutStrings($withoutComments);
        $requiredExtensions = $this->requiredExtensions($withoutComments);
        $actions = $this->actions($tokenView);

        foreach ($requiredExtensions as $extension) {
            if (in_array($extension, ['include', 'imapsieve', 'vnd.dovecot.pipe', 'vnd.dovecot.execute'], true)) {
                $warnings[] = 'Script requires extension outside Mailika local-rule scope: ' . $extension . '.';
            }
        }

        foreach ($actions as $action) {
            if (in_array($action, self::UNSUPPORTED_ACTIONS, true)) {
                $warnings[] = 'Script uses action outside Mailika local-rule scope: ' . $action . '.';
            }
        }

        if (!$this->balancedBraces($tokenView)) {
            $warnings[] = 'Script has unbalanced braces.';
        }

        if (!str_contains($script, self::OWNERSHIP_MARKER)) {
            $warnings[] = 'Script was not generated by Mailika and cannot be imported automatically.';
        }

        return new SieveScriptAnalysis(
            $bytes,
            $lines,
            str_contains($script, self::OWNERSHIP_MARKER),
            $requiredExtensions,
            $actions,
            array_values(array_unique($warnings)),
        );
    }

    /**
     * @return list<string>
     */
    private function requiredExtensions(string $script): array
    {
        preg_match_all(
            '/\brequire\s+(?:"((?:\\\\.|[^"\\\\])*)"|\[((?:.|\n)*?)\])\s*;/i',
            $script,
            $matches,
            PREG_SET_ORDER,
        );

        $extensions = [];
        foreach ($matches as $match) {
            $singleExtension = $match[1] ?? '';
            $extensionList = $match[2] ?? '';
            $values = $singleExtension !== '' ? [$singleExtension] : $this->quotedValues($extensionList);
            foreach ($values as $value) {
                $value = strtolower($this->unquoted($value));
                if ($value !== '') {
                    $extensions[$value] = $value;
                }
            }
        }

        ksort($extensions);

        return array_values($extensions);
    }

    /**
     * @return list<string>
     */
    private function quotedValues(string $value): array
    {
        preg_match_all('/"((?:\\\\.|[^"\\\\])*)"/', $value, $matches);
        return $matches[1];
    }

    /**
     * @return list<string>
     */
    private function actions(string $script): array
    {
        preg_match_all('/\b(' . implode('|', self::KNOWN_ACTIONS) . ')\b/i', $script, $matches);

        $actions = [];
        foreach ($matches[1] as $action) {
            $action = strtolower($action);
            $actions[$action] = $action;
        }

        ksort($actions);

        return array_values($actions);
    }

    private function balancedBraces(string $script): bool
    {
        $depth = 0;
        $length = strlen($script);

        for ($index = 0; $index < $length; $index++) {
            if ($script[$index] === '{') {
                $depth++;
            }

            if ($script[$index] === '}') {
                $depth--;
                if ($depth < 0) {
                    return false;
                }
            }
        }

        return $depth === 0;
    }

    private function withoutComments(string $script): string
    {
        $result = '';
        $length = strlen($script);
        $inString = false;

        for ($index = 0; $index < $length; $index++) {
            $char = $script[$index];
            $next = $script[$index + 1] ?? '';

            if ($inString) {
                $result .= $char;
                if ($char === '\\' && $next !== '') {
                    $index++;
                    $result .= $next;
                    continue;
                }

                if ($char === '"') {
                    $inString = false;
                }

                continue;
            }

            if ($char === '"') {
                $inString = true;
                $result .= $char;
                continue;
            }

            if ($char === '#') {
                while ($index < $length && $script[$index] !== "\n") {
                    $index++;
                }

                $result .= "\n";
                continue;
            }

            if ($char === '/' && $next === '*') {
                $index += 2;
                while ($index < $length && !($script[$index] === '*' && ($script[$index + 1] ?? '') === '/')) {
                    $result .= $script[$index] === "\n" ? "\n" : ' ';
                    $index++;
                }

                $index++;
                continue;
            }

            $result .= $char;
        }

        return $result;
    }

    private function withoutStrings(string $script): string
    {
        return (string) preg_replace('/"((?:\\\\.|[^"\\\\])*)"/', '""', $script);
    }

    private function unquoted(string $value): string
    {
        return stripcslashes($value);
    }
}
