<?php

declare(strict_types=1);

namespace Mailika\Filter;

final readonly class SieveScriptImporter
{
    private const OWNERSHIP_MARKER = '# Generated by Mailika';

    public function __construct(private SieveScriptAnalyzer $analyzer)
    {
    }

    /**
     * @return list<SieveRule>
     */
    public function import(string $script): array
    {
        $analysis = $this->analyzer->analyze($script);
        if (!$analysis->canImportAsLocalRules()) {
            throw new SieveScriptImportException('Only Mailika-generated Sieve scripts can be imported.');
        }

        $script = $this->normalize($script);
        $lines = explode("\n", $script);
        if ($lines[0] !== self::OWNERSHIP_MARKER) {
            throw new SieveScriptImportException('Only Mailika-generated Sieve scripts can be imported.');
        }

        $rules = [];
        $lineCount = count($lines);
        for ($index = 1; $index < $lineCount; $index++) {
            $line = trim($lines[$index]);
            if ($line === '' || $line === '# No enabled rules.' || str_starts_with($line, 'require ')) {
                continue;
            }

            if (!str_starts_with($line, '# ')) {
                throw new SieveScriptImportException('Sieve script contains statements outside Mailika local rules.');
            }

            $name = substr($line, 2);
            $index++;
            $ifLine = trim($lines[$index] ?? '');
            if (preg_match('/^if (.+) \{$/', $ifLine, $matches) !== 1) {
                throw new SieveScriptImportException('Sieve script contains a rule shape Mailika cannot import.');
            }

            $bodyLines = [];
            while (++$index < $lineCount) {
                $bodyLine = trim($lines[$index]);
                if ($bodyLine === '}') {
                    break;
                }

                if ($bodyLine !== '') {
                    $bodyLines[] = $bodyLine;
                }
            }

            if ($index >= $lineCount || trim($lines[$index] ?? '') !== '}') {
                throw new SieveScriptImportException('Sieve script has an unterminated rule block.');
            }

            $rules[] = $this->rule($name, $matches[1], $bodyLines);
        }

        if ($rules === [] && !str_contains($script, '# No enabled rules.')) {
            throw new SieveScriptImportException('Sieve script does not contain importable Mailika rules.');
        }

        return $rules;
    }

    /**
     * @param list<string> $bodyLines
     */
    private function rule(string $name, string $condition, array $bodyLines): SieveRule
    {
        if ($bodyLines === []) {
            throw new SieveScriptImportException('Sieve rule has no action.');
        }

        $stopProcessing = false;
        if (end($bodyLines) === 'stop;') {
            $stopProcessing = true;
            array_pop($bodyLines);
        }

        if (count($bodyLines) !== 1) {
            throw new SieveScriptImportException('Sieve rule has multiple actions.');
        }

        $conditionParts = $this->condition($condition);
        $actionParts = $this->action($bodyLines[0]);
        $rule = new SieveRule(
            $this->validateText($name, 128, 'Sieve rule name is invalid.'),
            true,
            $conditionParts['field'],
            $conditionParts['operator'],
            $conditionParts['value'],
            $actionParts['action'],
            $actionParts['target'],
            $stopProcessing,
            null,
            $actionParts['vacation_days'],
            $actionParts['vacation_subject'],
            $conditionParts['vacation_excluded_senders'],
            $actionParts['vacation_addresses'],
        );

        $this->validateRule($rule);
        return $rule;
    }

    /**
     * @return array{
     *     field: string,
     *     operator: string,
     *     value: string,
     *     vacation_excluded_senders: list<string>
     * }
     */
    private function condition(string $condition): array
    {
        $vacationExcludedSenders = [];
        if (preg_match('/^allof\((.+), not header :contains "From" (.+)\)$/', $condition, $matches) === 1) {
            $condition = $matches[1];
            $vacationExcludedSenders = $this->stringList($matches[2]);
        }

        $patterns = [
            'from' => '/^header :(contains|is) "From" ("(?:\\\\.|[^"\\\\])*")$/',
            'subject' => '/^header :(contains|is) "Subject" ("(?:\\\\.|[^"\\\\])*")$/',
            'to' => '/^header :(contains|is) \["To", "Cc"\] ("(?:\\\\.|[^"\\\\])*")$/',
            'any_header' => '/^header :(contains|is) \["From", "To", "Cc", "Subject"\] ("(?:\\\\.|[^"\\\\])*")$/',
            'body' => '/^body :(contains|is) ("(?:\\\\.|[^"\\\\])*")$/',
        ];

        foreach ($patterns as $field => $pattern) {
            if (preg_match($pattern, $condition, $matches) !== 1) {
                continue;
            }

            return [
                'field' => $field,
                'operator' => $matches[1],
                'value' => $this->unquoteToken($matches[2]),
                'vacation_excluded_senders' => $vacationExcludedSenders,
            ];
        }

        throw new SieveScriptImportException('Sieve rule condition is outside Mailika local-rule scope.');
    }

    /**
     * @return array{
     *     action: string,
     *     target: string|null,
     *     vacation_days: int|null,
     *     vacation_subject: string|null,
     *     vacation_addresses: list<string>
     * }
     */
    private function action(string $line): array
    {
        if ($line === 'discard;' || $line === 'keep;') {
            return [
                'action' => rtrim($line, ';'),
                'target' => null,
                'vacation_days' => null,
                'vacation_subject' => null,
                'vacation_addresses' => [],
            ];
        }

        if (preg_match('/^redirect ("(?:\\\\.|[^"\\\\])*");$/', $line, $matches) === 1) {
            return [
                'action' => 'redirect',
                'target' => $this->unquoteToken($matches[1]),
                'vacation_days' => null,
                'vacation_subject' => null,
                'vacation_addresses' => [],
            ];
        }

        if (preg_match('/^fileinto ("(?:\\\\.|[^"\\\\])*");$/', $line, $matches) === 1) {
            return [
                'action' => 'fileinto',
                'target' => $this->unquoteToken($matches[1]),
                'vacation_days' => null,
                'vacation_subject' => null,
                'vacation_addresses' => [],
            ];
        }

        if (str_starts_with($line, 'vacation ') && str_ends_with($line, ';')) {
            return $this->vacationAction(substr($line, strlen('vacation '), -1));
        }

        throw new SieveScriptImportException('Sieve rule action is outside Mailika local-rule scope.');
    }

    /**
     * @return array{
     *     action: string,
     *     target: string|null,
     *     vacation_days: int|null,
     *     vacation_subject: string|null,
     *     vacation_addresses: list<string>
     * }
     */
    private function vacationAction(string $payload): array
    {
        $offset = 0;
        $length = strlen($payload);
        $days = null;
        $subject = null;
        $addresses = [];
        $target = null;

        while ($offset < $length) {
            $offset = $this->skipWhitespace($payload, $offset);

            if (str_starts_with(substr($payload, $offset), ':addresses ')) {
                $offset += strlen(':addresses ');
                [$addresses, $offset] = $this->consumeStringList($payload, $offset);
                continue;
            }

            if (str_starts_with(substr($payload, $offset), ':days ')) {
                $offset += strlen(':days ');
                if (preg_match('/\G([0-9]+)/', $payload, $matches, 0, $offset) !== 1) {
                    throw new SieveScriptImportException('Sieve vacation days option is invalid.');
                }

                $days = (int) $matches[1];
                $offset += strlen($matches[1]);
                continue;
            }

            if (str_starts_with(substr($payload, $offset), ':subject ')) {
                $offset += strlen(':subject ');
                [$subject, $offset] = $this->consumeQuoted($payload, $offset);
                continue;
            }

            [$target, $offset] = $this->consumeQuoted($payload, $offset);
            $offset = $this->skipWhitespace($payload, $offset);
            if ($offset !== $length) {
                throw new SieveScriptImportException('Sieve vacation action has trailing content.');
            }
        }

        if ($target === null) {
            throw new SieveScriptImportException('Sieve vacation action is missing a response body.');
        }

        return [
            'action' => 'vacation',
            'target' => $target,
            'vacation_days' => $days,
            'vacation_subject' => $subject,
            'vacation_addresses' => $addresses,
        ];
    }

    /**
     * @return list<string>
     */
    private function stringList(string $value): array
    {
        [$values, $offset] = $this->consumeStringList($value, 0);
        if ($this->skipWhitespace($value, $offset) !== strlen($value)) {
            throw new SieveScriptImportException('Sieve string list has trailing content.');
        }

        return $values;
    }

    /**
     * @return array{0: list<string>, 1: int}
     */
    private function consumeStringList(string $value, int $offset): array
    {
        $offset = $this->skipWhitespace($value, $offset);
        if (($value[$offset] ?? '') !== '[') {
            [$single, $offset] = $this->consumeQuoted($value, $offset);
            return [[$single], $offset];
        }

        $offset++;
        $values = [];
        $length = strlen($value);
        while ($offset < $length) {
            $offset = $this->skipWhitespace($value, $offset);
            if (($value[$offset] ?? '') === ']') {
                $offset++;
                break;
            }

            [$item, $offset] = $this->consumeQuoted($value, $offset);
            $values[] = $item;
            $offset = $this->skipWhitespace($value, $offset);

            if (($value[$offset] ?? '') === ',') {
                $offset++;
                continue;
            }

            if (($value[$offset] ?? '') === ']') {
                continue;
            }

            throw new SieveScriptImportException('Sieve string list is invalid.');
        }

        if ($values === []) {
            throw new SieveScriptImportException('Sieve string list is empty.');
        }

        return [$values, $offset];
    }

    /**
     * @return array{0: string, 1: int}
     */
    private function consumeQuoted(string $value, int $offset): array
    {
        if (($value[$offset] ?? '') !== '"') {
            throw new SieveScriptImportException('Expected a quoted Sieve string.');
        }

        $offset++;
        $result = '';
        $length = strlen($value);
        while ($offset < $length) {
            $char = $value[$offset];
            if ($char === '\\') {
                if ($offset + 1 >= $length) {
                    throw new SieveScriptImportException('Sieve string has a dangling escape.');
                }

                $result .= $value[$offset + 1];
                $offset += 2;
                continue;
            }

            if ($char === '"') {
                return [$result, $offset + 1];
            }

            $result .= $char;
            $offset++;
        }

        throw new SieveScriptImportException('Sieve string is unterminated.');
    }

    private function unquoteToken(string $token): string
    {
        [$value, $offset] = $this->consumeQuoted($token, 0);
        if ($offset !== strlen($token)) {
            throw new SieveScriptImportException('Sieve string token is invalid.');
        }

        return $value;
    }

    private function skipWhitespace(string $value, int $offset): int
    {
        $length = strlen($value);
        while ($offset < $length && ctype_space($value[$offset])) {
            $offset++;
        }

        return $offset;
    }

    private function validateRule(SieveRule $rule): void
    {
        $this->validateText($rule->matchValue, 512, 'Sieve rule match value is invalid.');

        if (in_array($rule->action, ['fileinto', 'redirect', 'vacation'], true)) {
            $this->validateText((string) $rule->actionTarget, 512, 'Sieve rule action target is invalid.');
        }

        if ($rule->action === 'redirect' && filter_var($rule->actionTarget, FILTER_VALIDATE_EMAIL) === false) {
            throw new SieveScriptImportException('Sieve redirect target is invalid.');
        }

        if ($rule->action !== 'vacation' && $rule->vacationExcludedSenders !== []) {
            throw new SieveScriptImportException('Sieve sender exclusions require a vacation action.');
        }

        if ($rule->vacationDays !== null && ($rule->vacationDays < 1 || $rule->vacationDays > 365)) {
            throw new SieveScriptImportException('Sieve vacation days option is invalid.');
        }

        if ($rule->vacationSubject !== null) {
            $this->validateText($rule->vacationSubject, 255, 'Sieve vacation subject is invalid.');
        }

        $this->validateEmailList($rule->vacationExcludedSenders, 'Sieve vacation sender exclusion is invalid.');
        $this->validateEmailList($rule->vacationAddresses, 'Sieve vacation address is invalid.');
    }

    private function validateText(string $value, int $maxLength, string $message): string
    {
        $value = trim($value);
        if ($value === '' || mb_strlen($value) > $maxLength || preg_match('/[\x00-\x1F\x7F]/', $value) === 1) {
            throw new SieveScriptImportException($message);
        }

        return $value;
    }

    /**
     * @param list<string> $values
     */
    private function validateEmailList(array $values, string $message): void
    {
        if (count($values) > 20) {
            throw new SieveScriptImportException($message);
        }

        foreach ($values as $value) {
            if (filter_var($value, FILTER_VALIDATE_EMAIL) === false || mb_strlen($value) > 320) {
                throw new SieveScriptImportException($message);
            }
        }
    }

    private function normalize(string $script): string
    {
        $script = preg_replace('/^\xEF\xBB\xBF/', '', $script) ?? $script;
        return str_replace(["\r\n", "\r"], "\n", trim($script));
    }
}
