<?php

declare(strict_types=1);

namespace Mailika\Tests\Integration;

use Mailika\Auth\MailboxCredentials;
use Mailika\Config\Config;
use Mailika\Filter\ManageSievePublisher;
use PHPUnit\Framework\TestCase;

final class ExternalManageSieveFixtureTest extends TestCase
{
    protected function setUp(): void
    {
        if (getenv('MAILIKA_EXTERNAL_SIEVE_TESTS') !== '1') {
            self::markTestSkipped('Set MAILIKA_EXTERNAL_SIEVE_TESTS=1 and start a ManageSieve fixture to run.');
        }
    }

    protected function tearDown(): void
    {
        unset(
            $_ENV['MAILIKA_SIEVE_ENABLED'],
            $_ENV['MAILIKA_SIEVE_HOST'],
            $_ENV['MAILIKA_SIEVE_PORT'],
            $_ENV['MAILIKA_SIEVE_TLS'],
            $_ENV['MAILIKA_SIEVE_REQUIRE_TLS'],
            $_ENV['MAILIKA_ALLOWED_SIEVE_HOSTS'],
            $_ENV['MAILIKA_SIEVE_SCRIPT_NAME'],
        );
    }

    public function testPublishesGeneratedScriptAgainstExternalManageSieveFixture(): void
    {
        $host = getenv('MAILIKA_TEST_SIEVE_HOST') ?: '127.0.0.1';
        $port = $this->envInt('MAILIKA_TEST_SIEVE_PORT', 4190);
        $tls = $this->envString('MAILIKA_TEST_SIEVE_TLS', 'none');

        if (!$this->portOpen($host, $port)) {
            self::markTestSkipped('ManageSieve fixture is not reachable on the configured port.');
        }

        $_ENV['MAILIKA_SIEVE_ENABLED'] = 'true';
        $_ENV['MAILIKA_SIEVE_HOST'] = $host;
        $_ENV['MAILIKA_SIEVE_PORT'] = (string) $port;
        $_ENV['MAILIKA_SIEVE_TLS'] = $tls;
        $_ENV['MAILIKA_SIEVE_REQUIRE_TLS'] = $tls === 'none' ? 'false' : 'true';
        $_ENV['MAILIKA_ALLOWED_SIEVE_HOSTS'] = $host;
        $_ENV['MAILIKA_SIEVE_SCRIPT_NAME'] = $this->envString('MAILIKA_TEST_SIEVE_SCRIPT_NAME', 'mailika-test');

        $publisher = new ManageSievePublisher(Config::fromEnvironment(dirname(__DIR__, 2)));
        $credentials = new MailboxCredentials(
            $this->envString('MAILIKA_TEST_SIEVE_EMAIL', 'user@example.com'),
            $this->envString('MAILIKA_TEST_SIEVE_PASSWORD', 'secret'),
            'imap.example.com',
            993,
            true,
            'smtp.example.com',
            587,
            'starttls',
        );

        $script = "# Generated by Mailika\n# External ManageSieve fixture\nkeep;\n";
        $result = $publisher->publish($credentials, $script);

        self::assertTrue($result->published);
    }

    private function envInt(string $key, int $default): int
    {
        $value = getenv($key);
        return is_string($value) && is_numeric($value) ? (int) $value : $default;
    }

    private function envString(string $key, string $default): string
    {
        $value = getenv($key);
        return is_string($value) && $value !== '' ? $value : $default;
    }

    private function portOpen(string $host, int $port): bool
    {
        $connection = @fsockopen($host, $port, $errno, $error, 1.0);
        if ($connection === false) {
            return false;
        }

        fclose($connection);
        return true;
    }
}
