ALTER TABLE preferences
    ADD COLUMN IF NOT EXISTS theme VARCHAR(16) NOT NULL DEFAULT 'system',
    ADD COLUMN IF NOT EXISTS threaded_listing BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS messages_per_page INTEGER NOT NULL DEFAULT 50;
