<?php

declare(strict_types=1);

namespace Mailika\Tests\Unit;

use Mailika\Auth\MailboxCredentials;
use Mailika\Filter\ManageSieveClient;
use Mailika\Filter\SievePublishException;
use Mailika\Tests\Fixtures\FakeManageSieveConnection;
use PHPUnit\Framework\TestCase;

final class ManageSieveClientTest extends TestCase
{
    public function testPublishesScriptWithStartTlsPlainAuthAndSetActive(): void
    {
        $connection = new FakeManageSieveConnection([
            "\"IMPLEMENTATION\" \"Fake\"\r\n",
            "\"STARTTLS\"\r\n",
            "\"SASL\" \"PLAIN\"\r\n",
            "OK\r\n",
            "OK\r\n",
            "\"IMPLEMENTATION\" \"Fake TLS\"\r\n",
            "\"SASL\" \"PLAIN\"\r\n",
            "OK\r\n",
            "OK\r\n",
            "NO (NONEXISTENT) \"Script not found\"\r\n",
            "OK\r\n",
            "OK\r\n",
            "OK\r\n",
        ]);
        $credentials = new MailboxCredentials(
            'user@example.com',
            'secret',
            'imap.example.com',
            993,
            true,
            'smtp.example.com',
            587,
            'starttls',
        );
        $script = "# Generated by Mailika\nkeep;\n";

        $result = (new ManageSieveClient())->publish($connection, $credentials, 'mailika', $script, true);

        self::assertTrue($result->published);
        self::assertTrue($connection->tlsEnabled);
        self::assertTrue($connection->closed);
        self::assertSame("STARTTLS\r\n", $connection->writes[0]);
        self::assertSame("CAPABILITY\r\n", $connection->writes[1]);
        self::assertStringStartsWith('AUTHENTICATE "PLAIN" ', $connection->writes[2]);
        self::assertSame("GETSCRIPT \"mailika\"\r\n", $connection->writes[3]);
        self::assertSame("PUTSCRIPT \"mailika\" {" . strlen($script) . "+}\r\n" . $script, $connection->writes[4]);
        self::assertSame("SETACTIVE \"mailika\"\r\n", $connection->writes[5]);
        self::assertSame("LOGOUT\r\n", $connection->writes[6]);
    }

    public function testOverwritesExistingMailikaOwnedScript(): void
    {
        $existingScript = "# Generated by Mailika\nkeep;\n";
        $connection = new FakeManageSieveConnection([
            "\"IMPLEMENTATION\" \"Fake\"\r\n",
            "\"SASL\" \"PLAIN\"\r\n",
            "OK\r\n",
            "OK\r\n",
            '{' . strlen($existingScript) . "}\r\n",
            "OK\r\n",
            "OK\r\n",
            "OK\r\n",
            "OK\r\n",
        ], [$existingScript]);
        $script = "# Generated by Mailika\n# No enabled rules.\n";

        $result = (new ManageSieveClient())->publish($connection, $this->credentials(), 'mailika', $script, false);

        self::assertTrue($result->published);
        self::assertStringStartsWith('AUTHENTICATE "PLAIN" ', $connection->writes[0]);
        self::assertSame("GETSCRIPT \"mailika\"\r\n", $connection->writes[1]);
        self::assertSame("PUTSCRIPT \"mailika\" {" . strlen($script) . "+}\r\n" . $script, $connection->writes[2]);
        self::assertSame("SETACTIVE \"mailika\"\r\n", $connection->writes[3]);
        self::assertSame("LOGOUT\r\n", $connection->writes[4]);
    }

    public function testRefusesToOverwriteExternalScript(): void
    {
        $externalScript = "# Hand edited outside Mailika\nkeep;\n";
        $connection = new FakeManageSieveConnection([
            "\"IMPLEMENTATION\" \"Fake\"\r\n",
            "\"SASL\" \"PLAIN\"\r\n",
            "OK\r\n",
            "OK\r\n",
            '{' . strlen($externalScript) . "}\r\n",
            "OK\r\n",
        ], [$externalScript]);

        try {
            (new ManageSieveClient())->publish(
                $connection,
                $this->credentials(),
                'mailika',
                "# Generated by Mailika\nkeep;\n",
                false,
            );
            self::fail('Expected ManageSieve publish to reject an externally edited script.');
        } catch (SievePublishException $exception) {
            self::assertSame('Existing ManageSieve script was not generated by Mailika.', $exception->getMessage());
        }

        self::assertSame(2, count($connection->writes));
        self::assertTrue($connection->closed);
    }

    public function testRejectsStartTlsWhenServerDoesNotAdvertiseIt(): void
    {
        $connection = new FakeManageSieveConnection([
            "\"IMPLEMENTATION\" \"Fake\"\r\n",
            "\"SASL\" \"PLAIN\"\r\n",
            "OK\r\n",
        ]);

        $this->expectException(SievePublishException::class);

        (new ManageSieveClient())->publish($connection, $this->credentials(), 'mailika', "keep;\n", true);
    }

    public function testRejectsMissingSaslPlain(): void
    {
        $connection = new FakeManageSieveConnection([
            "\"IMPLEMENTATION\" \"Fake\"\r\n",
            "\"SASL\" \"SCRAM-SHA-256\"\r\n",
            "OK\r\n",
        ]);

        $this->expectException(SievePublishException::class);

        (new ManageSieveClient())->publish($connection, $this->credentials(), 'mailika', "keep;\n", false);
    }

    private function credentials(): MailboxCredentials
    {
        return new MailboxCredentials(
            'user@example.com',
            'secret',
            'imap.example.com',
            993,
            true,
            'smtp.example.com',
            587,
            'starttls',
        );
    }
}
