<?php

declare(strict_types=1);

namespace Mailika\Tests\Unit;

use Mailika\Filter\SieveScriptAnalyzer;
use PHPUnit\Framework\TestCase;

final class SieveScriptAnalyzerTest extends TestCase
{
    public function testAnalyzesMailikaGeneratedScript(): void
    {
        $script = <<<'SIEVE'
# Generated by Mailika
require ["fileinto", "vacation"];
if header :contains "Subject" "invoice" {
    fileinto "Archive";
    stop;
}
SIEVE;

        $analysis = (new SieveScriptAnalyzer())->analyze($script);

        self::assertTrue($analysis->mailikaOwned);
        self::assertSame(['fileinto', 'vacation'], $analysis->requiredExtensions);
        self::assertSame(['fileinto'], $analysis->actions);
        self::assertSame([], $analysis->warnings);
        self::assertTrue($analysis->canImportAsLocalRules());
    }

    public function testExternalComplexScriptIsSummarizedButNotImportable(): void
    {
        $script = <<<'SIEVE'
require ["fileinto", "include", "vnd.dovecot.pipe"];
if header :contains "Subject" "pipe should not count here" {
    pipe "spamc";
}
SIEVE;

        $analysis = (new SieveScriptAnalyzer())->analyze($script);

        self::assertFalse($analysis->mailikaOwned);
        self::assertSame(['fileinto', 'include', 'vnd.dovecot.pipe'], $analysis->requiredExtensions);
        self::assertSame(['pipe'], $analysis->actions);
        self::assertContains(
            'Script was not generated by Mailika and cannot be imported automatically.',
            $analysis->warnings,
        );
        self::assertContains('Script uses action outside Mailika local-rule scope: pipe.', $analysis->warnings);
        self::assertFalse($analysis->canImportAsLocalRules());
    }

    public function testIgnoresActionsInsideCommentsAndStrings(): void
    {
        $script = <<<'SIEVE'
# pipe "ignored";
/* execute "ignored"; */
require "fileinto";
if header :contains "Subject" "redirect vacation" {
    keep;
}
SIEVE;

        $analysis = (new SieveScriptAnalyzer())->analyze($script);

        self::assertSame(['keep'], $analysis->actions);
    }
}
