<?php

declare(strict_types=1);

namespace Mailika\Tests\Unit;

use Mailika\Filter\SieveRule;
use Mailika\Filter\SieveScriptAnalyzer;
use Mailika\Filter\SieveScriptCompiler;
use Mailika\Filter\SieveScriptImportException;
use Mailika\Filter\SieveScriptImporter;
use PHPUnit\Framework\TestCase;

final class SieveScriptImporterTest extends TestCase
{
    public function testImportsMailikaGeneratedRules(): void
    {
        $script = (new SieveScriptCompiler())->compile([
            new SieveRule(
                'Invoices',
                true,
                'from',
                'contains',
                'billing "ops" \\ inbox',
                'fileinto',
                'Archive "2026"',
            ),
            new SieveRule('Body', true, 'body', 'is', 'unsubscribe', 'keep', null, false),
            new SieveRule('Escalate', true, 'subject', 'contains', 'urgent', 'redirect', 'ops@example.com'),
            new SieveRule(
                'Away',
                true,
                'to',
                'is',
                'smoke@example.com',
                'vacation',
                'I am away.',
                true,
                null,
                7,
                'Away from mail',
                ['noreply@example.com', 'alerts@example.com'],
                ['smoke@example.com', 'team@example.com'],
            ),
        ]);

        $rules = $this->importer()->import($script);

        self::assertCount(4, $rules);
        self::assertSame('Invoices', $rules[0]->name);
        self::assertSame('from', $rules[0]->matchField);
        self::assertSame('contains', $rules[0]->matchOperator);
        self::assertSame('billing "ops" \\ inbox', $rules[0]->matchValue);
        self::assertSame('fileinto', $rules[0]->action);
        self::assertSame('Archive "2026"', $rules[0]->actionTarget);
        self::assertTrue($rules[0]->stopProcessing);

        self::assertSame('Body', $rules[1]->name);
        self::assertSame('body', $rules[1]->matchField);
        self::assertSame('is', $rules[1]->matchOperator);
        self::assertSame('keep', $rules[1]->action);
        self::assertFalse($rules[1]->stopProcessing);

        self::assertSame('redirect', $rules[2]->action);
        self::assertSame('ops@example.com', $rules[2]->actionTarget);

        self::assertSame('vacation', $rules[3]->action);
        self::assertSame(7, $rules[3]->vacationDays);
        self::assertSame('Away from mail', $rules[3]->vacationSubject);
        self::assertSame(['noreply@example.com', 'alerts@example.com'], $rules[3]->vacationExcludedSenders);
        self::assertSame(['smoke@example.com', 'team@example.com'], $rules[3]->vacationAddresses);
    }

    public function testImportsEmptyGeneratedScriptAsNoRules(): void
    {
        $rules = $this->importer()->import("# Generated by Mailika\n# No enabled rules.\n");

        self::assertSame([], $rules);
    }

    public function testRejectsMarkerStampedScriptOutsideCompilerShape(): void
    {
        $this->expectException(SieveScriptImportException::class);

        $this->importer()->import("# Generated by Mailika\nkeep;\n");
    }

    private function importer(): SieveScriptImporter
    {
        return new SieveScriptImporter(new SieveScriptAnalyzer());
    }
}
